# Generated by Django 4.0.4 on 2022-06-06 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodTaster', '0002_alter_recipe_ingredientamount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish_Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dishCode', models.IntegerField()),
                ('ingredientCode', models.IntegerField()),
                ('ingredientAmount', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredientAmount',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredientCode',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='name',
        ),
        migrations.AddField(
            model_name='recipe',
            name='steps',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
