# Generated by Django 4.0.4 on 2022-06-06 11:52

import FoodTaster.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodTaster', '0004_recipe_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='dishCode',
            field=models.IntegerField(db_column='pk', verbose_name=FoodTaster.models.Dish),
        ),
    ]
