# Generated by Django 4.0.4 on 2022-06-06 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodTaster', '0005_alter_recipe_dishcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='dishCode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FoodTaster.dish'),
        ),
    ]
