# Generated by Django 4.0.4 on 2022-06-07 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodTaster', '0009_alter_dish_ingredient_dishcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='dishCode',
            field=models.IntegerField(null=True),
        ),
    ]
